### ISSUE TITLE
dbmanager wont delete old backup files

### ISSUE THREAD

**Issue by betrcode** [lesterchan/wp-dbmanager#19]
dbmanager won't delete old backup files.
Maximum Backup Files is set to 12, but they are never deleted. 
Is there any logging of the attempts to delete? Perhaps there would be a clue there. I suspect a file system permissions issue, but all is green on the "Backup DB" page in wp-admin. "Excellent. You Are Good To Go."

Using version 2.77 with Wordpress 4.6.1, but I've had the same issue for many earlier versions too.

Any ideas?

**Comment by lesterchan** [comment]
Most likely it is a permission issue. The function to delete the backup is on line 374 https://github.com/lesterchan/wp-dbmanager/blob/master/wp-dbmanager.php#L374. You probably have to step through the function to see where it fails.

**Comment by betrcode** [comment]
Thanks for the reply @lesterchan 
Will investigate. You can close this issue if you like.
